<script lang="ts">
	let download_link: HTMLAnchorElement

	const generate_sample_file = (e: MouseEvent) => {
		e.preventDefault()
		const content = 'Hello, this is a sample file generated by SvelteKit!\nDownload example.'
		const blob = new Blob([content], { type: 'text/plain' })
		const url = URL.createObjectURL(blob)

		if (download_link) {
			download_link.href = url
			download_link.download = 'sample-download.txt'
			download_link.click()
			URL.revokeObjectURL(url)
		}
	}
</script>

<main class="container mx-auto p-8">
	<h1 class="mb-4 text-3xl font-bold">File Download Example</h1>
	<p class="mb-4">Click the button below to download a sample text file.</p>

	<button
		onclick={(e) => generate_sample_file(e)}
		class="rounded bg-blue-500 px-4 py-2 font-bold text-white hover:bg-blue-700"
	>
		Download Sample File
	</button>

	<a bind:this={download_link} style="display: none;"></a>
</main>
